flutter-es/website

es_ES/README.md

Correcciones de ortografia varias y enlaces a la web en español
close #3

readme ES revision 1

---

es_ES/README.md

corrección errata

---

es_ES/README.md

He pasado todo lo relativo a instalarse el repo a la wiki , para evitar confusiones en el readme.

refencia a wiki desde el readme eliminando duplicidad

---

es_ES/_includes/sidebar.html

ref: issues/26 cambiando a Gestos

---

.gitignore
es_ES/index.md

Algún acento,
La palabra Accede
Algún alt de imagen
Añadido a .gitignore la carpeta de settings de vcode.

correcciones varias

---

.gitignore
es_ES/_data/docs_cards.yml
es_ES/docs.md

traducción de docs.md

---

.gitignore
design-principles.md

Corrigiendo link roto por cambios en el repositorio flutter/engine

Broken link engine build sh

---

.gitignore
bootstrap-into-dart.md
fastlane.md

Fix broken links

---

es_ES/_includes/sidebar.html
es_ES/gestures.md
es_ES/layout.md

gestures.md

---

bootstrap-into-dart.md
design-principles.md
es_ES/testing.md
fastlane.md

Se agrego la traducción para testing

---

.gitignore
es_ES/get-started/learn-more.md

Algunos acentos.
Lista de correo en googlegroups.
close #34

Get started lean more corrección

---

bootstrap-into-dart.md
es_ES/cookbook/testing/widget-test-introduction.md
fastlane.md

traducción de widget-test-introduction

---

.gitignore
_config.yml
es_ES/cookbook/testing/mocking.md

traducción de mocking

---

es_ES/cookbook/index.md

indice de cookbook

---

.gitignore
_config.yml
es_ES/cookbook/testing/widget-test-tap-drag.md

traducción de widget_test_tap_drag

---

es_ES/index.md

Correcciones para tutear y algún acento

Correccione index.md túteo

---

bootstrap-into-dart.md
design-principles.md
es_ES/android-release-build.md
fastlane.md

Listo corregido enlaces rotos de la rama traduccion_android_release_build.
close #20

Traduccion android release build

---

es_ES/cookbook/design/fonts.md

traducción de fonts commit1

---

es_ES/cookbook/design/package-fonts.md

traducción de package-fonts commit1

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/cached-images.md
cookbook/images/fading-in-images.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

Corrección de enlaces a repositorio flutter/website

cambios en estructura de capertas de flutter/website

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/cached-images.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
support.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

Añadido enlace a reedit en support.md

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/cached-images.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
flutter-for-android.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

Añadido enlace a articulo sobre Linear Layouts

update desde flutter/website commit #1142

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/cached-images.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/android-release-build.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

Traido de la correción hecha en flutter/website PR # 1156
Correción aportada por nosotros a flutter.io en el issue # 1152 de repo original de flutter.io

Enlace que faltaba a gradlebuild

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/design/snackbars.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

traducción de snackbars commit1

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/cached-images.md
cookbook/images/fading-in-images.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
es_ES/cookbook/lists/long-lists.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

traducción de long_lists commit1

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
es_ES/cookbook/lists/horizontal-list.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

traducción de horizontal-list commit1

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
es_ES/cookbook/lists/grid-lists.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

traducción de grid-list commit1

---

es_ES/cookbook/design/themes.md

Traduccion cookbook/design/themes.md

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/design/orientation.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

traducción de orientation commit1

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
es_ES/cookbook/lists/basic-list.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

traducción de basic-list commit1

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
es_ES/cookbook/lists/mixed-list.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

traducción de mixed-list commit1

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/cached-images.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/design/tabs.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

la biblioteca Material (se nombra así como sustantivo en todas las traducciones)
El titulo del ejemplo de código no se puede traducir porque no concordaría con la imagen que viene a continuación

correciones cookbook/design/tabs.md

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/cached-images.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
es_ES/cookbook/index.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

Titulo de "Uso de fuentes personalizadas"

Correcion cookbook/index.md

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/cached-images.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

El título de la receta de Fade in no concuerda con el título dado en el otro PR y en cookbook/index.md
El title en el código no lo podemos traducir porque luego se muestra una imagen con este en ingles.

Correciones Cookbook/images/network-image.md

---

es_ES/_data/catalog/index.json
es_ES/_data/catalog/widgets.json
es_ES/widgets/accessibility.md
es_ES/widgets/animation.md
es_ES/widgets/assets.md
es_ES/widgets/async.md
es_ES/widgets/basics.md
es_ES/widgets/cupertino.md
es_ES/widgets/input.md
es_ES/widgets/interaction.md
es_ES/widgets/layout.md
es_ES/widgets/materialdesign.md
es_ES/widgets/painting.md
es_ES/widgets/scrolling.md
es_ES/widgets/styling.md
es_ES/widgets/text.md
widgets.md

close #138 
close #139 
close #140 
close #141 
close #142 
close #143 
close #144 
close #145 
close #146 
close #147 
close #148 
close #149 
close #150 
close #151

indices de widgets

---

es_ES/web-analogs.md

web-analogs.md

---

es_ES/cookbook/networking/authenticated-requests.md
es_ES/cookbook/networking/background-parsing.md
es_ES/cookbook/networking/fetch-data.md
es_ES/cookbook/networking/web-sockets.md

close #124 
close #125 
close #126 
close #127

Traducción de Cookbook/networking/

---

es_ES/cookbook/navigation/hero-animations.md

traducción de hero-animations commit1

---

es_ES/cookbook/navigation/navigation-basics.md

traducción de navigation-basics commit1

---

es_ES/cookbook/navigation/named-routes.md

traducción de named-routes commit1

---

_layouts/page.html
animations/hero-animations/index.md
animations/staggered-animations/index.md
cookbook/images/cached-images.md
cookbook/images/fading-in-images.md
cookbook/images/network-image.md
cookbook/navigation/hero-animations.md
design-principles.md
es_ES/cookbook/images/cached-images.md
es_ES/cookbook/images/fading-in-images.md
es_ES/cookbook/images/network-image.md
es_ES/cookbook/persistence/reading-writing-files.md
tutorials/animation/index.md
tutorials/interactive/index.md
tutorials/international/index.md
tutorials/layout/index.md

traducción de reading-writing-files.md

---

es_ES/_includes/setup/android-setup.md
es_ES/_includes/setup/get-sdk-win.md
es_ES/_includes/setup/get-sdk.md
es_ES/_includes/setup/ios-setup.md
es_ES/_includes/setup/path-mac-linux.md
es_ES/_includes/setup/system-mac.md
es_ES/_includes/setup/system-win.md
es_ES/get-started/editor.md
es_ES/get-started/install.md
es_ES/get-started/setup_macos.md
es_ES/get-started/test-drive.md

revisiones getstarted reacondicionado

---

fastlane.md

correciones fastlane.md desde upstream

---

ui-performance/index.md

cambios upstream ui-performance/index.md

---

platform-channels.md

upstream correccion platform-channels

---

es_ES/cookbook/navigation/passing-data.md

traducción cookbook/navigation/passing-data.md

---

_config.yml
es_ES/cookbook/gestures/ripples.md

traducción cookbook/gestures/ripples.md

---

_config.yml
es_ES/cookbook/forms/validation.md

traducción cookbok/forms/validation.md

---

_config.yml
es_ES/cookbook/forms/retrieve-input.md

traducción cookbook/forms/retrieve-input.md

---

_config.yml
es_ES/cookbook/maintenance/error-reporting.md

traducción cookbook/maintenance/error-reporting.md

---

_config.yml
es_ES/cookbook/forms/text-field-changes.md

traducción cookbook/forms/tex_field_changes.md

---

es_ES/catalog/samples/ExpansionTile_index.md

traducción catalog/samples/ExpaionTile_index

---

es_ES/catalog/samples/expansion_tile_sample.md

traducción catalog/samples/expansion_tile_sample

---

es_ES/catalog/samples/DefaultTabController_index.md

traducción catalog/samples/DefaultTabController_index

---

es_ES/catalog/samples/basic_app_bar.md

traducción catalog/samples/basic_app_bar

---

es_ES/catalog/samples/AppBar_index.md

traducción catalog/samples/AppBar_index

---

es_ES/catalog/samples/AnimatedListState_index.md

traducción catalog/samples/AnimatedListState_index

---

es_ES/catalog/samples/AnimatedList_index.md

traducción catalog/samples/AnimatedList_index

---

es_ES/catalog/samples/animated_list.md

traducción catalog/samples/animated_list

---

_config.yml
es_ES/cookbook/forms/text-input.md

traducción cookbook/forms/text-input.md

---

es_ES/developing-packages.md

developing packages

---

es_ES/catalog/samples/IconButton_index.md

traducción de IconButton_index commit1

---

tool/travis.sh

Buscando resolver problema con deploy en firebase

actualizacion de firebase-tools en travis.sh

---

es_ES/catalog/samples/TabController_index.md

traducción catalog/samples/TabController_index

---

es_ES/flutter-for-ios.md

traduccion flutter-for-ios aprobada

---

es_ES/faq.md

traducción aprobada de faq

---

es_ES/cookbook/testing/integration-test-scrolling.md

integration-test-scrolling correción aprobada, y revision daniel hecha

---

es_ES/cookbook/testing/integration-test-introduction.md

Integration test intro corregido

---

es_ES/codelabs/index.md

traduccion aprobada codelab index

---

es_ES/_data/showcases.yml
es_ES/showcase/index.md

traducción de showcase_index commit1

---

es_ES/tutorials/interactive/index.md

traducción tutorials/interactive/index.md

---

es_ES/flutter-for-react-native/index.md

traducción de react_native_idx commit1

---

es_ES/json.md

Traducción de json.md

---

es_ES/tutorials/animation/index.md

traducción tutorials/animation/index.md

---

es_ES/ui-performance/index.md

traducción de ui_performance_index commit1

---

es_ES/hot-reload.md

traduccion hot-reload.md

---

es_ES/search.md
search.md

close #57 
Hace que las búsquedas sean en nuestro dominio en lugar del flutter.io

traducción search.md

---

404.md
es_ES/404.md

traducción 404.md

---

es_ES/sdk-archive.md

traducción sdk-archive

---

es_ES/tutorials/international/index.md
tutorials/international/index.md

traduccion tutorials/intertanional/index.md

---

es_ES/flutter-for-android.md

traducción de flutter_for_android commit1

---

es_ES/bootstrap-into-dart.md

bootstrap-into-dart.md

---

es_ES/_data/showcases.yml

uptstream shocases

---

es_ES/get-started/learn-more.md

Correcciones getstarted/learn-more

---

es_ES/upgrading.md
es_ES/using-packages.md
upgrading.md
using-packages.md

traducción de root_upgrading commit1

---

es_ES/technical-overview.md

traducción de root_technical_overview commit1

---

es_ES/support.md

traducción de root_support commit1

---

es_ES/bug_reports.md

traducción de root_bug_reports commit1

---

es_ES/fastlane.md

Traducción fastlane.md

---

es_ES/animations/staggered-animations/index.md

Correción animations/staggered-animations/index.md

---

es_ES/ios-release-build.md

ios-release
